name: lint documentation
on:
  pull_request:
    paths:
      - "**.md"
jobs:
  mdlint:
    name: lint markDown file
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          globs: "**/*.md"

# https://github.com/DavidAnson/markdownlint
